### ISSUE TITLE
Gradle?

### ISSUE THREAD

**Issue by marie-bnl** [jagrosh/JLyrics#3]
Hello! I'm a beginner in Java development and I wanted to know if it's possible to use it with gradle, and if so, how? Thanks

**Comment by Zone-Infinity** [comment]
Saw this now , if you haven't figured it out
```gradle
implementation group: 'com.jagrosh', name: 'JLyrics', version: 'VERSION'
```

**Comment by Sanduhr32** [comment]
Latest version is `0.4`

**Comment by marie-bnl** [comment]
I missed that notification and I abandonned the project where I wanted to use JLyrics but hopefully this will be helpful for other gradle users! Thanks!
